resume_directory: ../data/input/example_resumes
summary_output_directory: ../data/output
data_schema_dir: ../data/schema

extractors:
 university:
  - [UCF, University of Central Florida, Central Florida]
  - [University of Florida]
  - [FSU, Florida State University]
  - [University of Miami]
  - [Georgia Institute of Technology, Georgia Tech]
  - [MIT, Massachussetts Institute of Technology]

 degree:
  - [Bachelor's, B.S.]
  - [Master's, M.S.]
  - [Associate's, A.S.]

 jobs:
  - intern
  - [developer, software developer, software engineer, engineer]
  - [Teacher, teaching assistant, professor, instructor]

 keywords:
  - Linux
  - Windows
  - [Mac, MacOS]
  - SQL
  - MySQL
  - [Postgres, Postgresql, PostgreSQL]
  - Oracle
  - [MongoDB, Mongo]
  - [java, JavaEE]
  - C
  - C++
  - C#
  - .NET
  - Matlab
  - R
  - python
  - Javascript
  - [sklearn, scikit-learn, sk-learn]
  - [tensorflow, tf, tensor-flow]
  - keras
  - h20
  - github
  - bitbucket
  - gitlab
  - sourceforge
  - gitkraken
